
version: '3'

services:
  fluentd:
#    image: ${FLUENTD_IMAGE}
    container_name: fluentd
    build:
      context: ./fluentd/context
      dockerfile: Dockerfile
    volumes:
      - ./fluentd/conf:/fluentd/etc
#      - /var/log/nginx:/var/log/nginx
    ports:
      - "24224:24224"
        #      - 1514:1514/udp
    environment:
      - "FLUENTD_CONF=fluentd.conf"





